api/urls.py
from . import views
from django.urls import path

app_name = 'api'
urlpatterns = [
    path('', views.apiOverview, name='api-overview'),
    path('city-list/', views.citylist_api, name='citylist'),
    path('weather/<str:city>/', views.weather_api, name='weather'),
    path('forecast/<int:cityid>/', views.forecast_api, name='forecast'),
]

weather/urls.py
from .sitemaps import ForecastSitemap, StaticSitemap
from weatherapp.views import robots_txt

from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib.sitemaps.views import sitemap

sitemaps = {'forecast': ForecastSitemap,
            'static': StaticSitemap}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps, 'template_name': 'mysitemap.xml'}, name='sitemap'),
    path('robots.txt', robots_txt),
]

urlpatterns += i18n_patterns(
    path('', include('weatherapp.urls')),
)

weatherapp/urls.py
from . import views
from .views import CityAutocomplete

from django.urls import path


app_name = 'weatherapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('addcityform/', views.addcityform, name='addcityform'),
    path('addcity/<int:city_id>', views.addcity, name='addcity'),
    path('deletecity/<int:city_id>', views.deletecity, name='deletecity'),
    path('forecast/<int:city_id>', views.forecast, name='forecast'),
    path('city-autocomplete/', CityAutocomplete.as_view(), name='city-autocomplete'),
    path('dbvacuum/', views.vacuum_db, name='vacuum_db'),
]

weatherapp/models.py
from django.db import models
from .fields import JSONField
from django.utils import timezone
from django.urls import reverse

from datetime import timedelta


class City(models.Model):
    name = models.CharField(max_length=100)
    opw_id = models.IntegerField(default=0)
    country = models.CharField(max_length=80, default='')
    state = models.CharField(max_length=80, default='')
    coord_lon = models.DecimalField(max_digits=12, decimal_places=6, default=0)
    coord_lat = models.DecimalField(max_digits=12, decimal_places=6, default=0)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return f'{self.name}, {self.country} ({round(self.coord_lon,2)}, {round(self.coord_lat,2)})'

    def get_absolute_url(self):     # used in xml sitemap
        return reverse('weatherapp:forecast', args=[str(self.pk)])

    def get_actual_weather(self):
        if self.weather_set.all().exists():
            w = self.weather_set.all().order_by('-loadingtime')[0]
            if w.is_actual():
                return w

    def get_actual_forecast(self):
        if self.forecast_set.all().exists():
            f = self.forecast_set.all().order_by('-loadingtime')[0]
            if f.is_actual():
                return f


class Weather(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE, null=False)
    loadingtime = models.DateTimeField(auto_now_add=True)
    weatherdata = JSONField()

    class Meta:
        ordering = ['-loadingtime']

    def __str__(self):
        return f'{self.city.name} {self.loadingtime.strftime("%d/%m/%Y, %H:%M:%S")}'

    def is_actual(self):
        timediff = timezone.now() - self.loadingtime
        if timediff <= timedelta(seconds=1800):
            return True
        else:
            return False


class Forecast(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE, null=False)
    loadingtime = models.DateTimeField(auto_now_add=True)
    forecastdata = JSONField()
    citydata = JSONField(default='')

    class Meta:
        ordering = ['-loadingtime']

    def __str__(self):
        return f'{self.city.name} {self.loadingtime.strftime("%d/%m/%Y, %H:%M:%S")}'

    def is_actual(self):
        timediff = timezone.now() - self.loadingtime
        if timediff <= timedelta(seconds=3600):
            return True
        else:
            return False


class Popularity(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE, null=False)
    pickeddate = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-pickeddate']

    def __str__(self):
        return self.city.name

weatherapp/forms.py
from .models import City
from django import forms
from django.utils.translation import gettext_lazy as _
from dal import autocomplete


class CityForm(forms.Form):
    picked_city = forms.ModelChoiceField(
        queryset=City.objects.all(),
        label='',
        widget=autocomplete.ModelSelect2(
            url='weatherapp:city-autocomplete',
            attrs={
                'data-placeholder': _('Введите город'),
                'data-minimum-input-length': 2,
                'data-theme': 'bootstrap4'
            }
        )
    )

weatherapp/views.py
from .models import City, Weather, Forecast, Popularity
from .forms import CityForm

from django.conf import settings
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.gis.geoip2 import GeoIP2
from django.db.models import Q
from django.contrib import messages
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.utils.translation import get_language
from django.db import connections, connection

import requests
from dal import autocomplete
from datetime import datetime, timedelta
import pandas as pd
import json
import csv
import pycountry


class CityAutocomplete(autocomplete.Select2QuerySetView):       # autocomplete field class
    def get_queryset(self):
        qs = City.objects.all()
        if self.q:
            qs = qs.filter(Q(name_en__istartswith=self.q) | Q(name_ru__istartswith=self.q.capitalize()) | Q(name_uk__istartswith=self.q.capitalize()))
            # search in 3 languages
        return qs


def GetCityIdbyName(cityname):
    try:
        res = City.objects.filter(Q(name_en__iexact=cityname) | Q(name_ru__iexact=cityname.capitalize()) | Q(name_uk__iexact=cityname.capitalize()))
        return res[0].id
    except Exception:
        pass


def GetGeoIPCity(ip):
    g = GeoIP2()
    # geoipdict = {'city': 'Kharkiv', 'continent_code': 'EU', 'continent_name': 'Europe',
    # 'country_code': 'UA', 'country_name': 'Ukraine', 'dma_code': None,
    # 'is_in_european_union': False, 'latitude': 49.982, 'longitude': 36.2566,
    # 'postal_code': '61145', 'region': '63', 'time_zone': 'Europe/Kiev'}
    try:
        geoipdict = g.city(ip)
    except Exception:
        geoipdict = {}
    return geoipdict


def getwinddir(spd):
    if 0 <= spd <= 22.5:
        spdstr = _('С')
    elif 22.5 < spd <= 67.5:
        spdstr = _('СВ')
    elif 67.5 < spd <= 112.5:
        spdstr = _('В')
    elif 112.5 < spd <= 157.5:
        spdstr = _('ЮВ')
    elif 157.5 < spd <= 202.5:
        spdstr = _('Ю')
    elif 202.5 < spd <= 247.5:
        spdstr = _('ЮЗ')
    elif 247.5 < spd <= 292.5:
        spdstr = _('З')
    elif 292.5 < spd <= 337.5:
        spdstr = _('СЗ')
    elif 337.5 < spd <= 360:
        spdstr = _('С')
    else:
        spdstr = ''
    return spdstr


def getpopulars(days=365):  # gets last 30 picked cities for popular block
    pl = Popularity.objects.filter(pickeddate__gt=timezone.now() - timedelta(days=days))[:30]
    pl = list(set([i.city for i in pl]))
    return pl


def getweather(request, c):
    if c.get_actual_weather():  # gets already loaded forecast from db
        print('w db')
        return c.get_actual_weather()
    else:
        print('w web')        # if no forecast in database requesting OPW
        current_lang = get_language()
        url = 'https://api.openweathermap.org/data/2.5/weather'
        prms = {'id': c.opw_id,
                'units': 'metric',
                'lang': current_lang,
                'appid': settings.OPW_API_KEY   # API key
                }

        try:
            res = requests.get(url, params=prms).json()
        except requests.ConnectionError:
            messages.add_message(request, messages.WARNING, _('Ошибка соединения'))
            return None
        else:
            w = Weather(city=c, weatherdata=res)
            w.save()
            return w


def index(request):

    # c_ip = request.META['REMOTE_ADDR']
    c_ip = request.META.get('HTTP_X_REAL_IP')   # client ip discovery for pythonanywhere
    # c_ip = ''  #ip for django dev server

    added_cities = request.session.get('added_cities', [])      # getting user`s added cities list from sessions

    geoipdata = GetGeoIPCity(c_ip)
    if geoipdata:
        print(geoipdata)
    if geoipdata and geoipdata['city'] is not None:           # if theres geoip city data for users ip
        if GetCityIdbyName(geoipdata['city']):      # looking for geoip cityname in db
            geoipdata['id'] = GetCityIdbyName(geoipdata['city'])
            if geoipdata['id'] not in added_cities:         # viewing geoip city by default
                added_cities = [geoipdata['id']] + added_cities
                request.session['added_cities'] = added_cities
    else:
        geoipdata = {}  # if theres no geoip data or no city in data

    # print(request.session['added_cities'])

    view_cities = []
    for cityid in added_cities:
        try:
            c = City.objects.get(pk=cityid)
        except City.DoesNotExist:
            messages.add_message(request, messages.WARNING, _('Несуществующий id. Обратитесь к администратору'))
            continue
        else:
            res = getweather(request, c)
            if res:
                res2 = res.weatherdata
                # print(res2)
                winfo = {
                    'cityid': cityid,
                    'city': c.name,
                    'country': c.country,
                    'descr': res2['weather'][0]['description'],
                    'icon': res2['weather'][0]['icon'],
                    'temp': res2['main']['temp'],
                    'temp_feels_like': res2['main']['feels_like'],
                    'pressure': round(res2['main']['pressure'] * 0.75006375541921),
                    'hum': res2['main']['humidity'],
                    'winds': round(res2['wind']['speed']),
                    'city_sunrise': datetime.utcfromtimestamp(res2['sys']['sunrise'] + res2['timezone']).strftime("%H:%M"),
                    'city_sunset': datetime.utcfromtimestamp(res2['sys']['sunset'] + res2['timezone']).strftime("%H:%M")
                }
                if 'deg' in res2['wind']:
                    winfo['winddir'] = getwinddir(res2['wind']['deg'])

                if 'gust' in res2['wind'] and round(res2['wind']['gust']) > round(res2['wind']['speed']):
                    winfo['gust'] = round(res2['wind']['gust'])

                if 'rain' in res2:
                    if '1h' in res2['rain']:
                        winfo['rain'] = res2['rain']['1h']
                    else:
                        winfo['rain'] = res2['rain']['3h']
                view_cities.append(winfo)

    form = CityForm()   # autocomplete form

    populars = getpopulars()

    context = {'city_info': view_cities, 'geoipdata': geoipdata,
               'form': form, 'populars': populars}

    return render(request, 'weatherapp/weather.html', context)


def addcityform(request):
    if request.method == 'POST':
        return HttpResponseRedirect(reverse('weatherapp:addcity', args=(int(request.POST['picked_city']),)))
    else:
        return HttpResponseRedirect(reverse('weatherapp:index'))


def addcity(request, city_id):
    try:
        c = City.objects.get(pk=city_id)
    except City.DoesNotExist:
        messages.add_message(request, messages.WARNING, _('Несуществующий id. Обратитесь к администратору'))
    else:
        added_cities = request.session.get('added_cities', [])
        if c.pk not in added_cities:
            added_cities.append(c.pk)
            request.session['added_cities'] = added_cities
            Popularity(city=c).save()
            messages.add_message(request, messages.SUCCESS, str(_('Вы добавили ')) + c.name)
        else:
            messages.add_message(request, messages.INFO, c.name + str(_(' уже добавлен. Попробуйте другой')))
    finally:
        return HttpResponseRedirect(reverse('weatherapp:index'))


def deletecity(request, city_id):
    added_cities = request.session.get('added_cities', [])
    if city_id in added_cities:
        added_cities.remove(city_id)
        request.session['added_cities'] = added_cities
        messages.add_message(request, messages.INFO, City.objects.get(pk=city_id).name + str(_(' удален')))
    return HttpResponseRedirect(reverse('weatherapp:index'))


def getforecast(request, c):
    if c.get_actual_forecast():  # gets already loaded forecast from db
        print('f db')
        return c.get_actual_forecast()
    else:
        print('f web')        # if no forecast in database requesting OPW
        current_lang = get_language()
        url = 'https://api.openweathermap.org/data/2.5/forecast'
        prms = {'id': c.opw_id,
                'units': 'metric',
                'lang': current_lang,
                'appid': settings.OPW_API_KEY}  # API key

        try:
            res = requests.get(url, params=prms).json()
        except requests.ConnectionError:
            messages.add_message(request, messages.WARNING, _('Ошибка соединения'))
            return None
        else:
            frct = Forecast(city=c, forecastdata=res['list'], citydata=res['city'])
            frct.save()
            return frct


def forecast(request, city_id):
    try:
        c = City.objects.get(pk=city_id)
    except City.DoesNotExist:
        messages.add_message(request, messages.WARNING, _('Несуществующий id. Обратитесь к администратору'))
        return HttpResponseRedirect(reverse('weatherapp:index'))
    else:
        forecast = getforecast(request, c)
        if forecast:
            fd = forecast.forecastdata
            cd = forecast.citydata
            city = {'city_timeshift': cd['timezone'],
                    'city_name': c.name,    # c['name'],
                    'city_country': c.country,
                    'city_sunrise': datetime.utcfromtimestamp(cd['sunrise'] + cd['timezone']).strftime("%H:%M"),
                    'city_sunset': datetime.utcfromtimestamp(cd['sunset'] + cd['timezone']).strftime("%H:%M")}

            forecast = []

            for datapoint in fd:
                winfo = {
                    'timetext': datetime.utcfromtimestamp(datapoint['dt'] + city['city_timeshift']).strftime('%H:%M'),
                    'datetext': datetime.utcfromtimestamp(datapoint['dt'] + city['city_timeshift']).strftime('%d.%m'),
                    'timeunix': (datapoint['dt'] + city['city_timeshift']) * 1000,

weatherapp/templates/weatherapp/admin_action_buttons.html
{% extends 'admin/change_list.html' %}

{% block object-tools %}
    <a href="{% url 'admin:import_json' %}">Import JSON</a>
    <br />
    {{ block.super }}
{% endblock %}

weatherapp/templates/weatherapp/admin_json_form.html
{% extends 'admin/base.html' %}

{% block content %}
    <div>
        <form action="." method="POST" enctype="multipart/form-data">
            {{ form.as_p }}
            {% csrf_token %}

                <button type="submit">Upload JSON</button>
        </form>
    </div>
    <br />

{% endblock %}

weatherapp/templates/weatherapp/forecast.html
{% extends "./index.html" %}
{% load i18n %}
{% block title %}
<title>{% trans 'Прогноз погоды в городе' %} {{city.city_name}}, {{city.city_country}}</title>
<meta name="description" content="{% trans 'Точный прогноз на каждые 3 часа в ближайшие 24 часа и на 5 дней в городе ' %} {{city.city_name}} {% trans '. Добавьте города и отслеживайте погоду и актуальный прогноз по ним.' %}" >
{% endblock %}

{% block content %}  
{% load static %}

  <div class="container mt-4">
    {% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show mb-0" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
    {% endfor %}
    {% endif %}    
    <h1 class="h1 mb-4" > {% trans 'Прогноз погоды в городе' %} {{city.city_name}} <i class="{{city.city_country|lower}} flag m-0"></i></h1> 
    <nav>
      <div class="nav nav-tabs" id="nav-tab" role="tablist">
        <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">{% trans 'На сутки' %}</a>
        <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">{% trans 'На 5 дней' %}</a>
      </div>
    </nav>
    <div class="tab-content" id="nav-tabContent">
      <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
        <div class="row" >
          <div class="col-5 col-xl pr-0 ">
            <li class="list-group-item border-right-0 border-top-0 pl-2 pl-md-4"><b>{% trans 'Время' %}</b></li>
            <li style="height:51px ;" class="list-group-item border-right-0 pl-2 pl-md-4"><b>{% trans 'Состояние' %}</b></li>
            <li class="list-group-item border-right-0 pl-2 pl-md-4"><b>{% trans 'Температура, °C' %}</b></li>
            <li class="list-group-item border-right-0 pl-2 pl-md-4"><b>{% trans 'Давление, мм.рт.ст.' %}</b></li>
            <li class="list-group-item border-right-0 pl-2 pl-md-4"><b>{% trans 'Влажность' %}, %</b></li>
            <li class="list-group-item border-right-0 pl-2 pl-md-4"><b>{% trans 'Ветер, м/с' %}</b></li>
            <li class="list-group-item border-right-0 pl-2 pl-md-4"><b>{% trans 'Осадки, мм' %}</b></li>
          </div>
          {% for cond in frcst %}
          <div class="col-2 col-xl pr-0 pl-0">
            <li class="list-group-item text-center border-right-0 border-top-0"><b>{{cond.timetext}}</b></li>
            <li class="list-group-item text-center border-right-0 p-0"><img src="https://openweathermap.org/img/w/{{cond.icon}}.png" alt="{{cond.descr}}" title="{{cond.descr}}"></li>
            <li class="list-group-item text-center border-right-0">{{cond.temp}}</li>
            <li class="list-group-item text-center border-right-0">{{cond.pressure}}</li>
            <li class="list-group-item text-center border-right-0">{{cond.humidity}}</li>
            <li class="list-group-item text-center border-right-0">{{cond.winddir}}, {{cond.winds}}</li>
            {% if cond.rain %}
            <li class="list-group-item text-center border-right-0">{{cond.rain}}</li>
            {% else %}
            <li class="list-group-item text-center border-right-0"> - </li>
            {% endif %}
            
            
          </div>
          {% endfor %}
        </div>
        
      </div>
      <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
        <div id="myChart">
        </div>
      </div>
    </div>
  </div>
  <script src="{% static 'weatherapp/js/zingchart.min.js' %}"></script>
  <script src="{% static 'weatherapp/js/chartconfig.js' %} "></script>
  <script>
  zingchart.render({ 
    id : 'myChart', 
    data : chartConfig({{graph.xstart|safe}}, {{graph.xfinish|safe}}, {{graph.temp_list|safe}}, {{graph.rain_list|safe}}, {{graph.pressure_list|safe}}, {{graph.winds_list|safe}}, {{graph.axis|safe}} ),
    height: 800,
    width: "100%" 
  });
  </script>
  {% endblock %}

weatherapp/templates/weatherapp/index.html
<!DOCTYPE html>
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
{% load static %}
{% load alternate_hreflang %}
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  {% block title %}{% endblock %}

  {% get_available_languages as languages %}
  {% for lang_code, lang_name in languages %}
      <link rel="alternate" hreflang="{{ lang_code }}" href="{% change_lang lang_code %}">
  {% endfor %}

  <link rel="icon" href="{% static 'favicon.ico' %}"  type="image/png">
  <link rel="shortcut icon" href="{% static 'favicon.ico' %}"  type="image/png">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" type="text/css">
  <link rel="stylesheet" href="{% static 'weatherapp/css/flag.min.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'weatherapp/css/main.css' %}" type="text/css">
  
</head>
{% load i18n %}
<body class="d-flex flex-column bg-light">
  <header class="border-bottom box-shadow p-1 py-md-3">
    <div class="container d-flex flex-column flex-md-row align-items-center p-md-2 ">
      <a class="navbar-brand my-0 mr-md-auto font-weight-bold text-dark" href="{% url 'weatherapp:index' %}"><span class="text-danger">W</span>eather.all</a>
      <nav class="navbar my-0 mr-md-3">
        <a class="p-2" href="{% url 'weatherapp:index' %}">{% trans 'Главная' %}</a>
        <a class="p-2" href="{% url 'api:api-overview' %}">API</a>

        {% if user.is_authenticated %}
        <a class="p-2" href="{% url 'admin:index' %}">{% trans 'Админка' %}</a>
        <a class="p-2" href="{% url 'weatherapp:vacuum_db' %}">db compress</a> 
        {% endif %} 
        
        <form class="navbar-form form-inline" action="{% url 'set_language' %}" method="post">
          {% csrf_token %}
          <input name="next" type="hidden" value="{{ redirect_to }}">
            <select onchange="this.form.submit()" class="custom-select" name="language">
                
                {% get_available_languages as LANGUAGES %}
                {% get_language_info_list for LANGUAGES as languages %}
                {% for language in languages %}
                    <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                        {{ language.name_local }} ({{ language.code }})
                    </option>
                {% endfor %}
            </select>
        </form>

      </nav>
    </div>
  </header>

  {% block content %}
  {% endblock %}

  <div class="footer text-muted border-top box-shadow p-3 mb-5 mt-5">
    
    <div class="container">
       
      &copy; Погода.тут 2020 <a class="pl-5" href="{% url 'sitemap' %}">XML Sitemap</a><br/>
      All	weather	and	forecast data is provided	under	terms	of CC BY-SA	4.0	International	license	by <a href="https://openweathermap.org/">Openweather	Ltd</a>. <br/>
      This product includes GeoLite2 data created by MaxMind, available from <a href="https://www.maxmind.com">maxmind.com</a>. <br/>
      
    </div>
  </div>

  <script src="https://code.jquery.com/jquery-2.2.4.js"></script>
  <script src="{% static 'weatherapp/js/bootstrap.js' %} "></script>
  <script>
      $("div.alert").alert();

      setTimeout(function() {
      $('.alert').fadeOut('slow');}, 3000 );
  </script>

</body>
</html> 
      

weatherapp/templates/weatherapp/weather.html
{% extends "./index.html" %}
{% load i18n %}
{% block title %}
<title>{% trans 'Актуальный и точный прогноз погоды в твоих городах!' %} </title>
<meta name="description" content="{% trans 'Погода сейчас и точный прогноз на 5 дней по всем городам мира. Добавьте города и отслеживайте погоду и актуальный прогноз по ним.' %}">
{% endblock %}

{% block content %} 
{% load static %}

  <div class="container">
    <div class="row d-flex flex-column justify-content-xl-between flex-md-row justify-content-around">
      <div class="col-md-8 text-left">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show mb-0" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
        {% endif %}    
      </div>
      <div class="col-md-4 mt-3 pb-3 text-right">
        {% if geoipdata %}
        <b>{% trans 'Вы находитесть в:' %}</b> <a href="{% url 'weatherapp:forecast' geoipdata.id %}" > {{geoipdata.city}}, {{geoipdata.country_name}} </a>  <br>
        {% endif %}
      </div>
    </div>
  </div> 


  <div class="container mt-2">
    <div class="row d-flex flex-column justify-content-xl-between flex-lg-row justify-content-center ">
      <div class="col-lg-5 col-auto">
        <div class="container mb-3 p-0 pb-2 ">
          <h1>{% trans 'Добавьте город' %}</h1>
          <p>{% trans 'и следите за погодой сразу в нескольких городах' %} </p>
          <form class="px-2 pt-1" action="{% url 'weatherapp:addcityform' %}" method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <!-- <input type="text" class="form-control" name="city" placeholder="Введите город"> -->
            <input type="submit" class=" btn btn-danger" name="send" value="{% trans 'Узнать погоду' %}">
          </form>
        </div>

        <div class="container mt-1 mb-3 my-xl-5 d-none d-sm-block">
          <p class="mb-1">{% trans 'Популярные пункты' %}</p>
          <div class="row row-cols-3 align-items-center align-self-center text-center border rounded bg-white ">
            {% for city in populars %}
            <div class="col my-1"> 
              <a class="" href="{% url 'weatherapp:addcity' city.pk %}"><i class="{{city.country|lower}} flag m-0"></i> {{city.name}}</a>
            </div>
            {% endfor %}
          </div> 
        </div>

      </div>
      <div class="col-xl-7 col-auto">
        <h1>{% trans 'Ваши города' %}</h1>
        <ul class="list-group">
        {% for info in city_info %}
        
          <li class="list-group-item list-group-item-danger mb-3 pt-1 pb-0 rounded">
            <div class="row">
              <div class="col-4 col-md-3 text-center px-1 pt-2">
                <h4 class="mb-md-3" >{{info.city}} <i class="{{info.country|lower}} flag m-0"></i></h4>  
                <div class="row d-flex justify-content-start flex-row ml-2">
                  <img src="https://openweathermap.org/img/w/{{info.icon}}.png" alt="{{info.descr}}" title="{{info.descr}}" width="60" height="60">
                  <p class="text-center mb-1 h5">{{info.temp}} °C</p>
                </div>
                <p class="text-center mb-1">{{info.descr}}</p>
              </div>
              <div class="col-5 col-md-6 pt-2 px-1 px-md-2 mt-0">
                <table class="table table-bordered table-sm mb-0">
                  <tbody>
                    <tr>  <td >{% trans 'Ощущается' %}</td>                  <td>{{info.temp_feels_like}} °C</td>            </tr>
                    <tr>  <td >{% trans 'Давление (мм.рт.ст.)' %}</td>       <td>{{info.pressure}}</td>                 </tr>
                    <tr>  <td >{% trans 'Влажность' %}</td>                  <td>{{info.hum}} %</td>                       </tr>
                    <tr>  <td >{% trans 'Ветер' %}</td>   <td>{% if info.winddir %} {{info.winddir}} , {% endif %} {{info.winds}} {% if info.gust %} - {{info.gust}} {% endif %} {% trans 'м/с' %}</td>  </tr>
                    {% if info.rain %}
                    <tr>  <td >{% trans 'Дождь' %}</td>                     <td>{{info.rain}} {% trans 'мм' %} </td>                       </tr>
                    {% endif %}

                  </tbody>
                </table>
              </div>

              <div class="col-3 d-flex flex-column justify-content-around mb-2 py-0 px-1">
                <a href="{% url 'weatherapp:deletecity' info.cityid %}" class="btn-sm close mr-0 ml-auto p-0" aria-label="{% trans 'Удалить город' %}">
                  <span aria-hidden="true">&times;</span>
                </a>
                <table class="table table-borderless table-sm mb-0 text-center">
                  <tbody>
                    <tr>  <td >{% trans 'Рассвет' %} - {{info.city_sunrise}}</td>  </tr>
                    <tr>  <td >{% trans 'Закат' %} - {{info.city_sunset}}</td>     </tr>
                  </tbody>
                </table>
                <a href="{% url 'weatherapp:forecast' info.cityid %}" class="btn btn-primary btn-sm mt-2">{% trans 'Прогноз на 5 дней' %}</a> 
              </div>
            </div>
          </li>
        {% endfor %}
        </ul>
      </div>
    </div>  
  </div>
  
  {{ form.media }}
  <link rel="stylesheet" href="{% static 'weatherapp/css/select2-bootstrap4.css' %}" type="text/css">
{% endblock %}
  